include:
  - project: 'server/ci-template'
    file: '/.gitlab-ci-react.yml'

variables:
  BASE_PATH: "/"

build:
  stage: build
  artifacts:
    paths:
    - node_modules
    - .next

package:cdn:
  stage: package
  script:
  - export DOCKER_TAG=`date +"%Y%m"`-${CI_PIPELINE_ID}
  - npx s3-cli sync .next/ s3://apiomui-assets/assets/$DOCKER_TAG/_next/ --acl-public --add-header="Cache-Control:public, max-age=31536000, immutable"

deploy:master:
  variables:
    API_URL: "https://api-dev.go1.co"
    CDN_PATH: "https://cdn.go1static.com/assets"
    ENV: "development"
    MEM: 128M

deploy:qa:k8s:
  variables:
    API_ENDPOINT: "https://api.qa.go1.cloud"
    CDN_PATH: "https://cdn.go1static.com/assets"
    MEM_MIN: 64Mi
    MEM_MAX: 128Mi

deploy:production:
  variables:
    API_URL: "https://api.go1.co"
    CDN_PATH: "https://cdn.go1static.com/assets"
    ENV: "production"
    MEM_MIN: 64Mi
    MEM_MAX: 128Mi
    ORG_ID: A6GD9
