include:
  - project: 'server/ci-template'
    file: '/.gitlab-ci-react.yml'

variables:
  BASE_PATH: "/"

build:
  stage: build
  artifacts:
    paths:
    - node_modules
    - .next
    - public

package:cdn:
  stage: package
  script:
  - export DOCKER_TAG=${CI_PIPELINE_ID}
  - npx s3-cli sync .next/ s3://apiomui-assets/assets/$DOCKER_TAG/_next/ --acl-public --add-header="Cache-Control:public, max-age=31536000, immutable"
  - npx s3-cli sync public/ s3://apiomui-assets/assets/$DOCKER_TAG/ --acl-public --add-header="Cache-Control:public, max-age=31536000, immutable"

deploy:master:k8s:
  variables:
    ENV: "development"
    MEM: 128M

deploy:qa:k8s:
  variables:
    MEM_MIN: 64Mi
    MEM_MAX: 128Mi

deploy:production:
  variables:
    ENV: "production"
    MEM_MIN: 256Mi
    ORG_ID: A6GD9
