include:
  - project: 'server/ci-template'
    file: '/.gitlab-ci-react.yml'

variables:
  BASE_PATH: "/r/app/player/"

deploy:master:
  variables:
    MEM: 128M
    API_ENDPOINT: https://api-dev.go1.co/

deploy:production:
  variables:
    MEM: 128M
    API_ENDPOINT: https://api.go1.co/
