include:
  - project: 'server/ci-template'
    file: '/.gitlab-ci-react.yml'

deploy:master:
  variables:
    MEM: 128M
    APP_API_URL: https://api-dev.go1.co/

deploy:production:
  variables:
    MEM: 128M
    APP_API_URL: https://api.go1.co/
