include:
  - project: 'server/ci-template'
    file: '/.gitlab-ci-react.yml'

variables:
  BASE_PATH: "/"

build:
  stage: build
  artifacts:
    paths:
    - node_modules
    - .next

deploy:master:
  variables:
    MEM: 128M

deploy:production:
  variables:
    MEM: 128M

deploy:qa:k8s:
  variables:
    MEM_MIN: 64Mi
    MEM_MAX: 128Mi
    ENV: "k8s-qa"

deploy:staging:k8s:
  variables:
    ENV: "staging"
    MEM_MIN: 64Mi
    MEM_MAX: 128Mi

deploy:production:k8s:
  variables:
    MEM_MIN: 64Mi
    MEM_MAX: 128Mi
    ENV: "prod"
    ORG_ID: A6GD9
