export const SIDEBAR_MENUS_INTEGRATIONS = {
  ADDONS: 'sidebar.integrations-addons',
  SCORM: 'sidebar.integrations-scorm',
  SCORM_AND_XAPI: 'sidebar.integrations-scorm-and-xapi',
  AUTOPILOT: 'sidebar.integrations-autopilot',
  STRIPE: 'sidebar.integrations-stripe',
  ZAPIER: 'sidebar.integrations-zapier',
  LTI_PROVIDER: 'sidebar.integrations-lti-provider',
  VETTRAK: 'sidebar.integrations-vettrak',
  WISENET: 'sidebar.integrations-wisenet',
  XERO: 'sidebar.integrations-xero',
  SUCCESS_FACTORS: 'sidebar.integrations-successfactors',
  CANVAS_LMS: 'sidebar.integrations-canvas-lms',
  MICROSOFT_AZURE: 'sidebar.integrations-azure',
  AZURE_B2C: 'sidebar.integrations-azure-b2c',
  COURSE_CATALOG: 'sidebar.integrations-course-catalog',
  SINGLE_SIGN_ON: 'sidebar.integrations-single-sign-on',
  DEVELOPER: 'sidebar.integrations-developers',
  USER_DATA_FEED: 'sidebar.integrations-user-data-feed',
  ORACLE: 'sidebar.integrations-oracle',
  MAS: 'sidebar.integrations-mas',
  NAS: 'sidebar.integrations-nas',
  LITMOS: 'sidebar.integrations-litmos',
};

export const SIDEBAR_MENUS_SETTINGS = {
  PORTAL_INFORMATION: 'sidebar.settings-portal-information',
  THEME: 'sidebar.settings-theme',
  CONFIGURATION: 'sidebar.settings-configuration',
  RECOMMENDATIONS: 'sidebar.settings-recommendations',
  PORTAL_CONTENT_SELECTION: 'sidebar.settings-portal-content-selection',
  NOTIFICATIONS: 'sidebar.settings-notifications',
  PLAN_AND_BILLING: 'sidebar.settings-plan-and-billing',
  SETUP_ACCOUNT: 'sidebar.settings-setup-account',
};
